#!/usr/bin/env perl

use strict;
use Smart::Comments;

my $debug = 1;
our %node_info ;
sub universe{
	my $cmd = "cd utility/rac/;sh universe.sh";
	&exe($cmd);
}

sub exe {
	my $cmd = shift;
	if( $debug) {
		print "$cmd\n";
	} else {
	  # system($cmd);
	}
}
sub analyze{
my $filename = "ip_map";
open my $fh,"< $filename" or die "Can not open $filename";
while(<$fh>){
	chomp;
	s/^\s*//;
	s/\s*$//;
	s/  / /g;
	next if /^#/;
	my ($ip,$name) = split ' ';
	if($name=~m/node(\d+)$/ or $name=~m/node(\d+)$/ ){
		my $node_num = $1;
		$node_info{$ip}=$node_num;
	}else{
		next;
	}
}
}
sub print_node_info{
	foreach(keys %node_info){
	print $_ ,"  ",$node_info{$_},"\n";
	}
}
sub no_passwd {
	my $user = shift || "root";
    my $passwd =  shift || "111111";
    my @nodelist=  keys %node_info;
    my $node= join "," ,@nodelist;
    my $cmd = "cd utility/nopasswd/; ./xmakessh  --user $user --pass  $passwd --nodes  $node  ; cd ../../ ";
    &exe( $cmd); 
}
sub scp_script{
	my $ip = shift;
	my $cmd = "scp -r ../oracle_deploy $ip:/root/";
	&exe( $cmd); 
}
sub user_env{
	my $num = shift;
	my $cmd = "cd utility/rac/;sh user_env.sh";
	&exe($cmd);
	$cmd =  "perl -p -i -e  's/rac1/rac".${num}."/' /home/oracle/.bash_profile";
	&exe($cmd);
	$cmd =  "perl -p -i -e  's/ASM1/ASM".${num}."/' /home/grid/.bash_profile";
	&exe($cmd);

}
sub set_hostname{
    my $name = shift;
    my $cmd = "sh utility/hostname.sh $name";
    &exe($cmd);
}
sub node{
	my $node_num = shift;
	&universe;
	&user_env($node_num);
    &set_hostname("node".$node_num);  
}

sub master{
    &no_passwd();
    
    foreach(keys %node_info){
    	&scp_script($_);
    	my $cmd = "ssh $_ 'chmod a+x  oracle_deploy -R ;cd oracle_deploy;  ./install ".$node_info{$_}." '";
    	&exe($cmd);
    }
    &no_passwd("oracle");
    &no_passwd("grid");
}
&analyze;
#&print_node_info;
### %node_info
if (@ARGV)
{
	my $node_num = $ARGV[0];
	die "$node_num is not a  node number" unless $node_num =~ m/\d+/;
	&node($node_num);
}else{
    &master;
}








