#!/usr/bin/env perl
#use Perl::Tidy;
use strict;
use Smart::Comments;

my $debug = 1;
our %node_info ;


sub analyze{
    my $filename = "ip_map";
    open my $fh,"< $filename" or die "Can not open $filename";
    while(<$fh>){
    	chomp;
    	s/^\s*//;
    	s/\s*$//;
    	s/  / /g;
    	next if /^#/;
    	my ( $ip,$name ) = split ' ';
    	if ( $name=~m/rac0*(\d+)$/i or $name=~m/node0*(\d+)$/i ){
    		my $node_num = $1;
    		$node_info{$ip}=$node_num;
    	}else{
    		next;
    	}
    }

}

sub universe{
    my $node_num = shift;
	my $cmd = "cd utility/rac/;sh universe.sh $node_num";
	&exe($cmd);
}

sub exe{
	my $cmd = shift;
	if( $debug) {
		print "$cmd\n";
	} else {
	   system($cmd);
	}
}
sub no_passwd {
	my $user = shift || "root";
    my $passwd =  shift || "111111";
    my @nodelist=  keys %node_info;
    my $node= join "," ,@nodelist;
    my $cmd = "cd utility/nopasswd/; ./xmakessh  --user $user --pass  $passwd --nodes  $node  ; cd ../../ ";
    &exe( $cmd); 
}
sub scp_script{
	my $ip = shift;
	my $cmd = "scp -r ../oracle_deploy $ip:/root/";
	&exe( $cmd); 
}
sub node{
	my $node_num = shift;
	&universe($node_num);
}

sub master{
    &no_passwd();
    foreach(keys %node_info){
    	&scp_script($_);
    	my $cmd = "ssh $_ 'chmod a+x  oracle_deploy -R ;cd oracle_deploy;  ./install ".$node_info{$_}." '";
    	&exe($cmd);
    }
    &no_passwd("oracle");
    &no_passwd("grid");
}

sub main{
    &analyze;
### %node_info
    if (@ARGV)
    {
    	my $node_num = $ARGV[0];
    	die "$node_num is not a  node number" unless $node_num =~ m/\d+/;
    	&node($node_num);
    }else{
        &master;
    }
}

&main;





