#!/bin/bash
cd `dirname $0`
echo "
usage: oracInst rac  <opt>

      -preOpt       enviroment prepare : setup user for oracle ,build ssh equivalent,create directory for oralce and so on .
      -grid         install grid software
      -asmca        create asm diskgroup for oracle data 
      -dbInstall    install database software only
      -dbca         create oracle database instance. 
      -all          install oracle all in one parameter . 
                      

      -un_dbca      uninstall oracle database instance.
      -un_db        uninstall oracle database software
      -un_asmca     drop oracle data diskgroup
      -un_grid      uninstall grid software
      -uninstall    uninstall a complete rac by rm , need reboot.
"
