#!/bin/bash
cd `dirname $0`
echo '
usage: oracInst rac  <opt>

      -preOpt    预处理，建用户，路径、配置ssh等，也可对介质进行检查等
      -grid      安装grid
      -asmca     建立asm管理
      -dbInstall 安装数据库
      -dbca      建库
      -all       相当于依次执行-preOpt -grid -asmca -dbInstall -dbca  
      -uninstall    卸载rac的安装

'
