#!/bin/bash

echo '
NAME
    oracInst  -  oracle installment scripts

Usage: 
    oraInst -h|-help|--help
    oracInst <Command>  <Option>

Command:
    single  : install standalone oracle database 
    rac     : install Real Cluster Application (RAC) oracle database

Option:

    oraInst single   -preOpt      prepare enviroment: unzip software,set env value, create user ,create directory and so on.
    oraInst single   -dbInstall   install database software only.
    oraInst single   -netca       setup listener
    oraInst single   -dbca        create database instance
    oraInst single   -all         install oracle all in one opt. the same as -preOpt, -dbInstall, -netca, -dbca,   one by one.
    oraInst single   -uninstall   uninstall oracle database 
    oraInst single   -h           help for  <oraInst single>   Command
    
    oraInst rac   -preOpt         enviroment prepare : setup user for oracle ,build ssh equivalent,create directory for oralce and so on .
    oraInst rac   -grid           install grid software
    oraInst rac   -asmca          create asm diskgroup for oracle data 
    oraInst rac   -dbInstall      install database software only
    oraInst rac   -dbca           create oracle database instance. 
    oraInst rac   -all            install oracle all in one parameter . 
    oraInst rac   -uninstall      uninstall a complete oracle rac, uninstall dbca,db,asmca,grid one by one .
    oraInst rac   -h              help for <oraInst rac> Command 

COPYRIGHT
    Copyright (C) 2014  Shalk
    
    Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
    
    The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
    
    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
    

'
